mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('notes/', include('notes.urls')),
    path('admin/', admin.site.urls),
]

notes/models.py
from django.db import models

class Note(models.Model):
    message = models.CharField(max_length=200)

notes/views.py
from django.views import generic
from django.urls import reverse_lazy
from .models import Note

class IndexView(generic.ListView):
    template_name = 'notes/index.html'
    context_object_name = 'notes_list'

    def get_queryset(self):
        """Return the all notes."""
        return Note.objects.all()

class CreateView(generic.edit.CreateView):
    template_name = 'notes/create.html'
    model = Note
    fields = ['message']
    success_url = reverse_lazy('notes:index') # more robust than hardcoding to /notes/; directs user to index view after creating a note

class UpdateView(generic.edit.UpdateView):
    template_name = 'notes/update.html'
    model = Note
    fields = ['message']
    success_url = reverse_lazy('notes:index')

class DeleteView(generic.edit.DeleteView):
    template_name = 'notes/delete.html' # override default of notes/note_confirm_delete.html
    model = Note
    success_url = reverse_lazy('notes:index')

notes/templates/notes/create.html
<form method="post">{% csrf_token %} {{ form.as_p }}
    <input type="submit" value="Save">
</form>

notes/templates/notes/delete.html
<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object.message }}"?</p>
    <input type="submit" value="Confirm">
</form>

notes/templates/notes/index.html
{% if note_list %}
<ul>
    {% for note in note_list %}
    <li>
        {{ note.message }}
        <span><a href="{% url 'notes:update' note.id %}">edit</a></span>
        <span><a href="{% url 'notes:delete' note.id %}">delete</a></span>
    </li>
    {% endfor %}
</ul>
{% else %}
<p>You haven't written any notes!</p>
{% endif %}
<a href="{% url 'notes:create' %}">Write something new</a>
<br>
<p>~~~~~~~~~~</p>

notes/templates/notes/update.html
<form method="post">{% csrf_token %} {{ form.as_p }}
    <input type="submit" value="Update">
    <a href="{% url 'notes:delete' note.id %}">delete</a>
</form>